image: python:3.6
services:
  - docker:dind

stages:
  - deploy

build:
  stage: deploy
  script:    
    - pip install awscli --upgrade
    - aws s3 cp s3://wons-public-files/wons-data.zip wons-data.zip
    - unzip wons-data.zip
    - rm wons-data.zip
    - docker login registry.gitlab.com -u $gitlab_registry_user -p $gitlab_registry_password
    - docker build -t registry.gitlab.com/dhermyt/wons:$CI_COMMIT_REF_SLUG .
    - docker push registry.gitlab.com/dhermyt/wons:$CI_COMMIT_REF_SLUG

